version: '3.9'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: te-django
    container_name: django
    command: >
      sh -c "python manage.py migrate && python manage.py collectstatic --noinput && python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - db
      - redis

  db:
    image: postgres:13
    container_name: postgres
    environment:
      POSTGRES_DB: ex
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 8695
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql

  redis:
    image: redis:6
    container_name: redis
    ports:
      - "6379:6379"

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - web

  celery:
    build: .
    command: celery -A myproject worker --loglevel=info
    volumes:
      - .:/app
    depends_on:
      - db
      - redis

volumes:
  postgres_data:
