# Generated by Django 5.1.5 on 2025-01-27 23:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='habit',
            name='reward_or_related_habit',
        ),
    ]
