# Generated by Django 5.1.5 on 2025-01-28 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0002_remove_habit_reward_or_related_habit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
