# Generated by Django 5.1.5 on 2025-01-25 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0002_habit_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
