# Generated by Django 5.1.5 on 2025-01-25 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0003_habit_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='created_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='habit',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
