# Generated by Django 5.1.5 on 2025-01-25 12:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0005_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='name',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
